import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#0e0e10',
        'surface-dim': '#131315',
        'on-error': '#690005',
        'surface-variant': '#353437',
        'secondary-fixed': '#4ffbe6',
        'surface-container-high': '#2a2a2c',
        'on-background': '#e5e1e4',
        'surface': '#131315',
        'secondary-fixed-dim': '#17deca',
        'tertiary-container': '#8798ff',
        'error-container': '#93000a',
        'on-primary-fixed-variant': '#5e289b',
        'primary-fixed': '#eedbff',
        'primary-container': '#bb86fc',
        'on-secondary-container': '#005950',
        'on-tertiary-fixed': '#00105c',
        'on-primary': '#460283',
        'on-error-container': '#ffdad6',
        'error': '#ffb4ab',
        'on-tertiary-container': '#13298f',
        'on-tertiary': '#08218a',
        'primary': '#dab9ff',
        'surface-container-highest': '#353437',
        'tertiary': '#bac3ff',
        'inverse-on-surface': '#313032',
        'surface-tint': '#dab9ff',
        'on-surface': '#e5e1e4',
        'surface-container': '#201f22',
        'tertiary-fixed': '#dee0ff',
        'secondary': '#46f5e0',
        'on-surface-variant': '#cdc3d4',
        'on-primary-container': '#4c0f89',
        'outline-variant': '#4b4452',
        'surface-container-low': '#1c1b1d',
        'on-secondary-fixed': '#00201c',
        'on-primary-fixed': '#2a0053',
        'background': '#131315',
        'inverse-primary': '#7743b5',
        'on-secondary-fixed-variant': '#005048',
        'secondary-container': '#00d8c4',
        'on-secondary': '#003731',
        'inverse-surface': '#e5e1e4',
        'primary-fixed-dim': '#dab9ff',
        'tertiary-fixed-dim': '#bac3ff',
        'surface-bright': '#39393b',
        'outline': '#978d9d',
        'on-tertiary-fixed-variant': '#293ca0',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
export default config
